# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources
    - name: Restore dependencies
      run: dotnet restore ./subtrack.Tests
    - name: Build
      run: dotnet build ./subtrack.Tests --no-restore
    - name: Test
      run: dotnet test ./subtrack.Tests --no-build --verbosity normal
