# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "dev", "master" ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    # temp solution until we upgrade to .net 8. same for restore workload
    - uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
        
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore workload 
      run: dotnet workload restore        
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
